name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm test
      run: |
        npm test
      env:
        CI: true
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Test* ${{ matrix.node-version }}'
        mention: 'here'
        mention_if: 'failure'
        channel: '#wowaffixes'
        url: ${{ secrets.SLACK_WEBHOOK }}
